# Generated by Django 3.1.2 on 2020-10-16 01:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='buys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('price', models.IntegerField()),
                ('POST', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Buys',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='SabadKharid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('product', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'سبد خرید',
            },
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000)),
                ('code_posti', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='POSTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', ckeditor.fields.RichTextField()),
                ('photo_post', models.ImageField(help_text='Upload your photo', upload_to='posts/%Y/%D')),
                ('photo_post1', models.ImageField(blank=True, help_text='Upload your photo', null=True, upload_to='posts/%Y/%D')),
                ('photo_post2', models.ImageField(blank=True, help_text='Upload your photo', null=True, upload_to='posts/%Y/%D')),
                ('photo_post3', models.ImageField(blank=True, help_text='Upload your photo', null=True, upload_to='posts/%Y/%D')),
                ('photo_post4', models.ImageField(blank=True, help_text='Upload your photo', null=True, upload_to='posts/%Y/%D')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('Discount', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('unavailable', 'ناموجود'), ('available', 'موجود')], max_length=500)),
                ('published', models.CharField(choices=[('published', 'پست شده'), ('draft', 'پیش نویس')], max_length=500)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True, help_text='Post insertion date')),
                ('tags', models.CharField(max_length=1000)),
                ('category', models.ManyToManyField(to='app.Category')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Grouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='دسته بندی اصلی این پست را وارد نمائید.')),
                ('category', models.ManyToManyField(to='app.Category', verbose_name='دسته بندی های این دسته را وارد کنید.')),
            ],
            options={
                'verbose_name_plural': 'Groupings',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('comment', models.CharField(max_length=500)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, verbose_name='submit')),
                ('answer', models.TextField(blank=True, help_text='Your Answer To This Comment!', null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.posts')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
